version: '3'

services:
  wg-easy:
    build:
      context: ./wgProjectServersUtil  # Убедитесь, что этот путь правильный и содержит Dockerfile
      dockerfile: Dockerfile  # Проверьте, что Dockerfile находится здесь
    command: npm run serve  # Убедитесь, что команда корректна для запуска вашего приложения
    ports:
      - "800:800/udp"  # Проверьте, что этот порт открыт на хосте
      - "500:500/tcp"  # Проверьте, что этот порт открыт на хосте
    cap_add:
      - NET_ADMIN  # Убедитесь, что эти привилегии действительно необходимы
      - SYS_MODULE

  next-app:
    build:
      context: ./wgBot  # Убедитесь, что этот путь правильный и содержит Dockerfile
      dockerfile: Dockerfile  # Проверьте, что Dockerfile находится здесь
    environment:
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      - ./wgBot:/app  # Убедитесь, что это правильный путь к исходному коду
    ports:
      - "3000:3000"  # Проверьте, что этот порт открыт на хосте
    command: npm start  # Убедитесь, что команда корректна для запуска вашего приложения
