version: '3'
services:
  wg-easy:
    build:
      context: .  # Укажите директорию, в которой находится Dockerfile
      dockerfile: ./Dockerfile  # Убедитесь, что Dockerfile находится в указанной директории
    command: npm run serve  # Убедитесь, что это правильная команда для запуска вашего приложения
    volumes:
      - ./src:/app  # Обратите внимание на отсутствие конечного слэша
       # Если этот volume вам не нужен, можете закомментировать
    ports:
      - "800:800/udp"
      - "500:500/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    
